project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
      - text: "Hands-on Exercise 1"
        href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "Hands-on Exercise 2"
        href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
      - text: "Hands-on Exercise 3A"
        href: "Hands-on_Ex/Hands-on_Ex03A/Hands-on_Ex03A.html"
      - text: "Hands-on Exercise 3B"
        href: "Hands-on_Ex/Hands-on_Ex03B/Hands-on_Ex03B.html" 
      - text: "Hands-on Exercise 4A"
        href: "Hands-on_Ex/Hands-on_Ex04A/Hands-on_Ex04A.html" 
      - text: "Hands-on Exercise 4B"
        href: "Hands-on_Ex/Hands-on_Ex04B/Hands-on_Ex04B.html" 
      - text: "Hands-on Exercise 4C"
        href: "Hands-on_Ex/Hands-on_Ex04C/Hands-on_Ex04C.html"
      - text: "Hands-on Exercise 4D"
        href: "Hands-on_Ex/Hands-on_Ex04D/Hands-on_Ex04D.html"  
      - text: "Hands-on Exercise 5"
        href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"  
      - text: "Hands-on Exercise 6"
        href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
      - text: "Hands-on Exercise 8A"
        href: "Hands-on_Ex/Hands-on_Ex08A/Hands-on_Ex08A.html"
      - text: "Hands-on Exercise 8B"
        href: "Hands-on_Ex/Hands-on_Ex08B/Hands-on_Ex08B.html"
      - text: "Hands-on Exercise 8C"
        href: "Hands-on_Ex/Hands-on_Ex08C/Hands-on_Ex08C.html"
      - text: "Hands-on Exercise 9A"
        href: "Hands-on_Ex/Hands-on_Ex09A/Hands-on_Ex09A.html"  
      - text: "Hands-on Exercise 9B"
        href: "Hands-on_Ex/Hands-on_Ex09B/Hands-on_Ex09B.html"
      - text: "Hands-on Exercise 9C"
        href: "Hands-on_Ex/Hands-on_Ex09C/Hands-on_Ex09C.html"
      - text: "Hands-on Exercise 9D"
        href: "Hands-on_Ex/Hands-on_Ex09D/Hands-on_Ex09D.html"
      - text: "Hands-on Exercise 9E"
        href: "Hands-on_Ex/Hands-on_Ex09E/Hands-on_Ex09E.html" 
      - text: "Hands-on Exercise 10"
        href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"   
        
    - text: "Take-Home Exercise"
      menu: 
      - text: "Take-Home Exercise 1"
        href: "Take-home_Ex/Take-home_Ex_1/Take-home_Ex01.html"  
      - text: "Take-Home Exercise 1B"
        href: "Take-home_Ex/Take-home_Ex_1B/Take-home_Ex01B.html" 
      - text: "Take-Home Exercise 2"
        href: "Take-home_Ex/Take-home_Ex_2/Take-home_Ex_2.html" 
      - text: "Take-Home Exercise 3"
        href: "Take-home_Ex/Take-home_Ex_3/Take-home_Ex_3.html"   
    - text: "In-Class Exercise"
      menu: 
      - text: "In-Class Exercise 5"
        href: "In-Class_Ex/In-Class_Ex_05/MC1.html"  
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

